### ISSUE TITLE
JSON data rendering

### ISSUE THREAD

**Issue by nblumhardt** [messagetemplates/messagetemplates-csharp#11]
I just whipped up: https://gist.github.com/nblumhardt/769e34782b300dbbf8b9d4a407802eeb in response to a question on the Serilog group. The idea is to render JSON data via JSON.NET out through MessageTemplates.

It's pretty simple, but hard to discover if you're not familiar with the library. @adamchester where do you think this should live? I'm happy to whip up a NuGet package, here or as a personal repo, or else write it up for the README. Thoughts?

**Comment by adamchester** [comment]
Looks like a great sample scenario for the README

**Comment by nblumhardt** [comment]
Done, ta.
