### ISSUE TITLE
Perhaps we should simplify the namespaces?

### ISSUE THREAD

**Issue by SimonCropp** [messagetemplates/messagetemplates-csharp#22]
![image](https://user-images.githubusercontent.com/122666/39284300-e14ca756-4955-11e8-80f1-45306afdfcc8.png)

**Comment by nblumhardt** [comment]
:+1: .. maybe in conjunction with #20 ?

**Comment by SimonCropp** [comment]
so one namespace?

**Comment by nblumhardt** [comment]
Needs some investigation and a proposal, I guess - the eventual direction we go with #20 would have an impact on how many types the library would expose.
