### ISSUE TITLE
Consider dropping some supported frameworks

### ISSUE THREAD

**Issue by SimonCropp** [messagetemplates/messagetemplates-csharp#24]
currently the following are supported net452;net35;net40;netstandard1.0;netstandard1.3

but net35 was released over a decade ago, and support for 4.0 ended over two years ago https://en.wikipedia.org/wiki/.NET_Framework_version_history#Overview

**Comment by adamchester** [comment]
Since we did all the work required to make old versions supported, I am in favour of releasing v1.0 first, and then drop support for the really old frameworks.

**Comment by SimonCropp** [comment]
@adamchester sounds good to me. want to assign this to a 2.0 milestone?
